header:
  version: 1

machine: qemux86-64
distro: poky
target:
  - helloworld

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.0"
    layers:
      .: excluded

  poky:
    url: "https://git.yoctoproject.org/poky"
    branch: mickledore
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-test:
    layers:
      meta-test:

local_conf_header:
  meta-test: |
    # Some useful lines you may want to copy to your site.conf for development
    # INHERIT += "rm_work"
    # EXTRA_IMAGE_FEATURES = "debug-tweaks"